"""
scripts/17_centroid_knockdown_table.py

Builds the "knock-down" regression table for the manuscript (Table~\\ref{tab:ols}):
the first city-level alignment regression, which showed the centroid overlap measure
is a city-SIZE artifact and motivated the switch to cluster co-membership.

It reproduces, EXACTLY, the two regressions whose numbers already appear in the
manuscript via macros in manuscript/generated/stats.tex (generated by
scripts/export_paper_assets.py):

  Centroid measure (the artifact)
    (1) semantic_overlap ~ log(papers) + log(projects)          HC3           -> statOlsRsqModelOne
    (2)     + country fixed effects                             cluster(country) -> statOlsRsqModelTwo
        betas from (2): statOlsBetaPapers, statOlsBetaProjects
  Cluster co-membership measure (the fix)
    (3) cluster_overlap ~ log(cl. papers) + log(cl. projects)   HC3           -> statClusterOlsRsq
        p-values from (3): statClusterSizePapersP, statClusterSizeProjectsP

Both use the same inputs the macros use (city_level.csv, all_artifacts.csv) and NO
embedding model. The script prints its numbers next to the current macro values so any
drift (e.g. after city_level.csv is regenerated) is visible.

Output: manuscript/tab_centroid_knockdown.tex   (\\label{tab:ols})
"""

import io
import re
import subprocess
import numpy as np
import pandas as pd
import statsmodels.formula.api as smf
from pathlib import Path

ROOT   = Path(__file__).parent.parent
ART    = ROOT / "data" / "processed" / "all_artifacts.csv"
CITY   = ROOT / "data" / "processed" / "city_level.csv"
STATS  = ROOT / "manuscript" / "generated" / "stats.tex"
OUTTEX = ROOT / "manuscript" / "tab_centroid_knockdown.tex"

MIN_DOCS = 8   # non-noise docs of EACH type per city (matches export_paper_assets.py)


def read_committed_city_level() -> pd.DataFrame:
    """Read the COMMITTED (git HEAD) city_level.csv, not the working-tree copy.

    stats.tex (the manuscript's live numbers) was generated by
    export_paper_assets.py from the committed city_level.csv. The working tree
    currently holds an uncommitted edit to that file (2 fewer cities), which has
    not been flowed through the pipeline. Building the table from the committed
    vintage keeps it numerically identical to the prose and the stat macros. If
    the working-tree edit is later committed and export_paper_assets.py re-run,
    re-run this script too and it will track the new vintage.
    """
    try:
        blob = subprocess.run(
            ["git", "-C", str(ROOT), "show", "HEAD:data/processed/city_level.csv"],
            capture_output=True, text=True, check=True).stdout
        print("Centroid regression: using COMMITTED (HEAD) city_level.csv")
        return pd.read_csv(io.StringIO(blob))
    except Exception as e:  # not a git checkout, file untracked, etc.
        print(f"  (git show failed: {e}; falling back to working-tree city_level.csv)")
        return pd.read_csv(CITY)


# -- (1)-(2) Centroid regression: semantic_overlap ~ size ----------------------
# Mirrors export_paper_assets.stage_overlap_regression().

city = read_committed_city_level()
city["log_n_papers"]   = np.log1p(city["n_papers"])
city["log_n_projects"] = np.log1p(city["n_projects"])

m1 = smf.ols("semantic_overlap ~ log_n_papers + log_n_projects",
             data=city).fit(cov_type="HC3")
m2 = smf.ols("semantic_overlap ~ log_n_papers + log_n_projects + C(country)",
             data=city).fit(cov_type="cluster", cov_kwds={"groups": city["country"]})


# -- (3) Cluster co-membership regression: cluster_overlap ~ size --------------
# Mirrors export_paper_assets.stage_cluster().

art = pd.read_csv(ART, low_memory=False)
art["city_key"] = art["city"].astype(str).str.strip().str.lower()
valid = art[art["cluster_label"] >= 0]
K = int(valid["cluster_label"].max()) + 1

def freq(sub):
    v = np.zeros(K)
    for c, n in sub["cluster_label"].value_counts().items():
        v[int(c)] = n
    nrm = np.linalg.norm(v)
    return v / nrm if nrm > 0 else None

rows = []
for ck, g in valid.groupby("city_key"):
    pg, qg = g[g.type == "paper"], g[g.type == "project"]
    if len(pg) == 0 or len(qg) == 0:
        continue
    p, q = freq(pg), freq(qg)
    if p is None or q is None:
        continue
    rows.append({"city_key": ck, "n_cl_papers": len(pg), "n_cl_projects": len(qg),
                 "cluster_overlap": float(np.dot(p, q))})
co = pd.DataFrame(rows)
co["log_n_cl_papers"]   = np.log1p(co["n_cl_papers"])
co["log_n_cl_projects"] = np.log1p(co["n_cl_projects"])
dense = co[(co.n_cl_papers >= MIN_DOCS) & (co.n_cl_projects >= MIN_DOCS)].copy()

m3 = smf.ols("cluster_overlap ~ log_n_cl_papers + log_n_cl_projects",
             data=dense).fit(cov_type="HC3")


# -- Drift check against the macros already in the manuscript ------------------

def macro_val(name):
    txt = STATS.read_text()
    m = re.search(r"\\newcommand\{\\" + name + r"\}\{([^}]*)\}", txt)
    return m.group(1) if m else "(missing)"

checks = [
    ("statOlsRsqModelOne",      f"{m1.rsquared:.3f}"),
    ("statOlsRsqModelTwo",      f"{m2.rsquared:.3f}"),
    ("statOlsBetaPapers",       f"{m2.params['log_n_papers']:+.4f}"),
    ("statOlsBetaProjects",     f"{m2.params['log_n_projects']:+.4f}"),
    ("statClusterOlsRsq",       f"{m3.rsquared:.3f}"),
    ("statClusterSizePapersP",  f"{m3.pvalues['log_n_cl_papers']:.3f}"),
    ("statClusterSizeProjectsP",f"{m3.pvalues['log_n_cl_projects']:.3f}"),
]
print(f"Centroid sample N={int(m1.nobs)} | Cluster dense sample N={int(m3.nobs)} "
      f"({dense['city_key'].nunique()} cities)\n")
print(f"{'macro':<26}{'recomputed':>12}{'in stats.tex':>16}   drift?")
for name, rec in checks:
    cur = macro_val(name)
    flag = "" if cur == rec else "  <-- DRIFT"
    print(f"{name:<26}{rec:>12}{cur:>16}{flag}")


# -- Emit the regression table (label tab:ols) --------------------------------

def cell(m, key):
    if key not in m.params.index:
        return "—", ""
    b, se, p = m.params[key], m.bse[key], m.pvalues[key]
    stars = "***" if p < 0.001 else "**" if p < 0.01 else "*" if p < 0.05 \
            else r"$\dagger$" if p < 0.10 else ""
    return f"{b:.4f}{stars}", f"({se:.4f})"

# row keys differ by measure (total counts for centroid, clustered counts for cluster)
papers_keys   = {"m1": "log_n_papers", "m2": "log_n_papers", "m3": "log_n_cl_papers"}
projects_keys = {"m1": "log_n_projects", "m2": "log_n_projects", "m3": "log_n_cl_projects"}
mods = {"m1": m1, "m2": m2, "m3": m3}

def row(disp, keymap):
    cs, ss = [], []
    for tag in ("m1", "m2", "m3"):
        c, s = cell(mods[tag], keymap[tag])
        cs.append(c); ss.append(s)
    return (f"{disp} & " + " & ".join(cs) + r" \\",
            r"& " + " & ".join(ss) + r" \\[4pt]")

pr = row(r"$\log(\text{papers})$", papers_keys)
pj = row(r"$\log(\text{projects})$", projects_keys)

lines = [
    "% Auto-generated by scripts/17_centroid_knockdown_table.py — do not edit by hand.",
    r"\begin{table}[htbp]",
    r"\centering",
    (r"\caption{The first city-level alignment regression, and why it retired the "
     r"centroid measure. Columns~(1)--(2) regress the centroid overlap "
     r"(\texttt{semantic\_overlap}, the cosine between a city's paper- and "
     r"project-embedding centroids) on city size; column~(3) regresses the cluster "
     r"co-membership overlap (\texttt{cluster\_overlap}, the cosine between the two "
     r"cluster-frequency vectors) on the same size controls. Size explains most of the "
     r"centroid measure and almost none of the cluster measure. Size is total document "
     r"counts in~(1)--(2) and clustered (non-noise) counts in~(3), which is why the "
     r"cluster sample is the "
     rf"{int(m3.nobs)} cities with $\geq {MIN_DOCS}$ clustered documents of each type. "
     r"Coefficients are not comparable across measures (the two overlaps live on "
     r"different scales); the readable contrast is the $R^2$ and the size significance. "
     r"Standard errors in parentheses: HC3 in~(1) and~(3), clustered by country in~(2). "
     r"$\dagger p<0.10$, $^{*}p<0.05$, $^{**}p<0.01$, $^{***}p<0.001$.}"),
    r"\label{tab:ols}",
    r"\begin{tabular}{lccc}",
    r"\toprule",
    r"& \multicolumn{2}{c}{Centroid overlap} & Cluster overlap \\",
    r"\cmidrule(lr){2-3} \cmidrule(lr){4-4}",
    r"& (1) & (2) & (3) \\",
    r"\midrule",
    pr[0], pr[1],
    pj[0], pj[1],
    r"\midrule",
    r"Country FE & No & Yes & No \\",
    r"$N$ (cities) & " + " & ".join(str(int(m.nobs)) for m in (m1, m2, m3)) + r" \\",
    r"$R^2$ & " + " & ".join(f"{m.rsquared:.3f}" for m in (m1, m2, m3)) + r" \\",
    r"\bottomrule",
    r"\end{tabular}",
    r"\end{table}",
]
OUTTEX.write_text("\n".join(lines) + "\n")
print(f"\nWrote {OUTTEX}")
